/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.feemanagementsystem;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Shubham Pathak
 */
public class SignUpPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage.class.getName());

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtpfield = new javax.swing.JPasswordField();
        txtcpfield = new javax.swing.JPasswordField();
        txtcnumber = new javax.swing.JTextField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnclear = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        lablcpassworderror = new javax.swing.JLabel();
        lablpassworderror = new javax.swing.JLabel();
        lablcnumbererror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 160));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("D.O.B");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Contact Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 150, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, -1));

        txtuname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, -1));

        txtpfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpfieldActionPerformed(evt);
            }
        });
        txtpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txtpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 200, -1));

        txtcpfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfieldActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 200, -1));

        txtcnumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 200, -1));

        txtdob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 200, 30));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 110, 40));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 110, 40));

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 110, 40));

        lablcpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lablcpassworderror.setForeground(new java.awt.Color(255, 0, 0));
        lablcpassworderror.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lablcpassworderrorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lablcpassworderrorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lablcpassworderrorKeyTyped(evt);
            }
        });
        getContentPane().add(lablcpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 240, 30));

        lablpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lablpassworderror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lablpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 240, 30));

        lablcnumbererror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lablcnumbererror.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(lablcnumbererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        validation();
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtcpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfieldActionPerformed

    private void txtpfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyPressed
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyPressed

    private void txtpfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyReleased
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyReleased

    private void txtpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyTyped
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyTyped

    private void txtcnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyPressed
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyPressed

    private void txtcnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyReleased
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyReleased

    private void txtcnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyTyped
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyTyped

    private void lablcpassworderrorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lablcpassworderrorKeyPressed
        // TODO add your handling code here:
        currentPasswordCheck();
    }//GEN-LAST:event_lablcpassworderrorKeyPressed

    private void lablcpassworderrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lablcpassworderrorKeyReleased
        // TODO add your handling code here:
        currentPasswordCheck();
    }//GEN-LAST:event_lablcpassworderrorKeyReleased

    private void lablcpassworderrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lablcpassworderrorKeyTyped
        // TODO add your handling code here:
        currentPasswordCheck();
    }//GEN-LAST:event_lablcpassworderrorKeyTyped
   
    String fname, lname,uname, password, cpassword, mnumber;
    Date dob;

        void insertData(){
        SimpleDateFormat s1 = new SimpleDateFormat("yyy-MM-dd");
        String dob1 = s1.format(dob);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feemanagementdb", "root", "shubham");
            
            String query = "INSERT INTO signup VALUES(?,?,?,?,?,?,?)";
            PreparedStatement smt = con.prepareStatement(query);
            
            smt.setInt(1, getId());
            smt.setString(2, fname);
            smt.setString(3, lname);
            smt.setString(4, uname);
            smt.setString(5, password);
            smt.setString(6, dob1);
            smt.setString(7, mnumber);
            int i = smt.executeUpdate();
            if(i > 0){
                JOptionPane.showMessageDialog(this, "Record Inserted Succesfully");
            }
            else{
                JOptionPane.showMessageDialog(this, "Record Not Inserted Succesfully");

            }
               
        }
        catch(Exception e){
            
        }
    }
    boolean validation(){
        fname = txtfname.getText();
        lname = txtlname.getText();
        uname = txtuname.getText();
        password = txtpfield.getText();
        cpassword = txtcpfield.getText();
        dob = txtdob.getDate();
        mnumber = txtcnumber.getText();
        
        if(fname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your First Name");
            return false;
        }
        if(lname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your Last Name");
            return false;
        }
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your Username");
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your Password");
            return false;
        }
        if(cpassword.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your Confirm Password");
            return false;
        }
        if(dob.equals(null)){
            JOptionPane.showMessageDialog(this, "Please Enter Your Date Of Birth");
            return false;
        }
        if(mnumber.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Your Contact Number");
            return false;
        }
        
        return true;
    }
    void passwordCheck(){
        password = txtpfield.getText();
        if(password.length() >= 8){
            lablpassworderror.setText("");
        }
        else{
            lablpassworderror.setText("Enter 8 Digit Password");
        }
    }
    void mobileCheck(){
        mnumber = txtcnumber.getText();
        if(mnumber.length() == 10){
            lablcnumbererror.setText("");
            
        }
        else{
            lablcnumbererror.setText("Please Enter 10 Digit Number");
        }
    }
    void currentPasswordCheck(){
        cpassword = txtcpfield.getText();
        if(cpassword.equals(password)){
            lablcpassworderror.setText("");
        }
        else{
            lablcpassworderror.setText("Please Enter Correct Password");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lablcnumbererror;
    private javax.swing.JLabel lablcpassworderror;
    private javax.swing.JLabel lablpassworderror;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JPasswordField txtcpfield;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpfield;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
